services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/var/www/html
    depends_on:
      - mongodb
    networks:
      - laravel_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ../mongo_data:/data/db
    networks:
      - laravel_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  laravel_network:
    driver: bridge

volumes:
  mongo_data:


